export const GET_USER_INFO = 'GET_USER_INFO'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_USER_RES = 'SET_USER_RES'
export const EDIT_PROFILE = 'EDIT_PROFILE'
export const EDIT_PROFILE_MESSAGE = 'edit_profile_message'
