export const GET_PRODUCT_LIST = 'get_product_list'
export const ADD_PRODUCT_LIST = 'add_product_list'
export const PRODUCT_LOADING = 'product_loading'
export const ADD_PRODUCT = 'add_product'
export const UPDATE_PRODUCT = 'update_product'
export const DELETE_PRODUCT = 'delete_product'
export const UPDATE_PRODUCT_MESSAGE = 'update_product_message'
export const DELETE_PRODUCT_MESSAGE = 'delete_product_message'
export const ADD_PRODUCT_MESSAGE = 'add_product_message'
export const SET_TOTAL_RECODE = 'set_total_recode'
export const GET_PRODUCT_INFO_BY_ID = 'get_product_info_by_id'
export const SET_PRODUCT_INFO_BY_ID = 'set_product_info_by_id'
export const SET_PRODUCT_RES_BY_ID = 'set_product_res_by_id'
export const GET_ALL_CATEGORIES_LIST = 'get_all_catagories_list'
export const SET_ALL_CATEGORIES_LIST = 'set_all_categories_list'

export const GET_PRODUCT_REVIEWS = 'get_product_reviews'
export const SET_PRODUCT_REVIEWS = 'set_product_reviews'
export const SET_PRODUCT_REVIEWS_RES = 'set_product_reviews_res'

export const DELETE_REVIEWS = 'delete_reviews'
export const DELETE_REVIEWS_RES = 'delete_reviews_res'

export const ADD_PRODUCT_VARIANTS = 'add_product_variants'
export const ADD_PRODUCT_VARIANTS_RES = 'add_product_variants_res'
export const UPDATE_PRODUCT_VARIANTS = 'update_product_variants'
export const UPDATE_PRODUCT_VARIANTS_RES = 'update_product_variants_res'
export const DELETE_PRODUCT_VARIANTS = 'delete_product_variants'
export const DELETE_PRODUCT_VARIANTS_RES = 'delete_product_variants_res'
