export const GET_USER_LIST = 'get_user_list'
export const ADD_USER_LIST = 'add_user_list'
export const USER_LOADING = 'user_loading'
export const UPDATE_USER = 'update_user'
export const DELETE_USER = 'delete_user'
export const UPDATE_USER_MESSAGE = 'update_user_message'
export const DELETE_USER_MESSAGE = 'delete_user_message'
export const SET_TOTAL_RECODE = 'set_total_recode'
